### ISSUE TITLE
有没有数据分享一下呢？

### ISSUE THREAD

**Issue by StevenLOL** [YeahHuang/Al_surface_defect_detection#1]
有没有数据分享一下呢？

**Comment by YeahHuang** [comment]
天池官方要求数据保密了呐.... 所以据保密协议我也不太方便上传不好意思...

**Comment by QQ2737499951** [comment]
> 有没有数据分享一下呢？

链接：https://pan.baidu.com/s/1R2RW-ql0UoO_m5C0X_BYNA 提取码：w7tn

**Comment by jiec-msft** [comment]
Thank you @QQ2737499951

**Comment by TangDL** [comment]
> > 有没有数据分享一下呢？
> 
> 链接：https://pan.baidu.com/s/1R2RW-ql0UoO_m5C0X_BYNA 提取码：w7tn
请问下，这个训练数据的annot享一下呢？
> 
> 链接：https://pan.baidu.com/s/1R2RW-ql0UoO_m5C0X_BYNA 提取码：w7tn
请问下，这个训练数据的annotation是要自己制作吗
