### ISSUE TITLE
Did this package implement OHEM?

### ISSUE THREAD

**Issue by bygreencn** [YeahHuang/Al_surface_defect_detection#10]
As your blog's description, OHEM is more important part to improve mAP, but I could not find any implement from all winner‘s release? Do you known any runnable project?

**Comment by YeahHuang** [comment]
Thx for asking~~

Here is the link for the project which combines DCN(Deformable ConvNets) and OHEM:  https://github.com/msracver/Deformable-ConvNets 

After listening to the final speech of the competition, I know that the way the 3rd team realized OHEM was to modify the configuration of the official DCN code(shown above). With the help of this DCN code, you only need to set the OHEM flag of its configuration file to True to apply OHEM techniques.

Hope  this answer will help u a little :)
