### ISSUE TITLE
数据预处理？

### ISSUE THREAD

**Issue by henbucuoshanghai** [YeahHuang/Al_surface_defect_detection#11]
图片直接定位 预测？

**Comment by henbucuoshanghai** [comment]
图片切割？

**Comment by YeahHuang** [comment]
我曾经尝试过用mask-rcnn先定位切割再做classification/detection. 但是最后的准确率/mAP均降低了， 我觉得是因为本身比赛方已经对图片进行了整理， 大小尺寸都是统一的， 所以自己的 切割+resize反而会负面的影响结果。

**Comment by henbucuoshanghai** [comment]
小白 好难入门医学检测
请问为什么先切割？不懂

**Comment by YeahHuang** [comment]
首先 我这个代码是针对天池的铝型材表面缺陷检测比赛的哦，和医学检测无关。
其次， 关于先切割后分类会positive/negative影响最后准确率的问题， 过于general了哈， 可能需要你自行google才能全面的了解哦～～

**Comment by henbucuoshanghai** [comment]
是的我现在有一个和铝板材类似的   所以有点不懂请教一下
1初赛直接在原图上训练网络二分类？好坏？
2复赛的标注呢？用什么网络检测：识别哪一类并bbox框出来？

**Comment by henbucuoshanghai** [comment]
那怎样识别哪一类及回归bbox呢?

**Comment by YeahHuang** [comment]
关于第一个问题 请自行查看比赛官网哈～ 1）是多分类。包括正常/缺陷1/缺陷2/缺陷3....    2)是的。分类+定位缺陷
关于第二个问题  过于general， 可能需要你自行google才能全面的了解哦～～
