### ISSUE TITLE
请教一下初赛的模型

### ISSUE THREAD

**Issue by bittergourd1224** [YeahHuang/Al_surface_defect_detection#12]
由于我这边只需要分类好坏而不需要将缺陷具体标出，感觉和初赛的题目比较类似。问一下你初赛提交的模型是什么呢？似乎项目里没有上传，请问是有官方版本之类的可以下载吗？谢谢！

**Comment by YeahHuang** [comment]
上传在项目里了哦 就是Season1-classification 可以读一下该文件夹的Readme 了解参考模型哈～

**Comment by bittergourd1224** [comment]
多谢回复！
我看了代码，但还是不太明白。import model_v4这里是什么模型呢，这个没在项目里呀。还有model_name = 'ljh_main_inception2'这个模型也没有……
我可以理解后一个模型是在前一个基础上训练出来的是吗？但是没有从前到后训练的代码额。
不好意思我是个新手，还烦请解答一下，多谢多谢！

**Comment by YeahHuang** [comment]
因为就像我readme里写的。你可以refer to[ @hubertchen ](https://github.com/herbert-chen/tianchi_lvcai)的github链接 进一步理解初赛的分类问题哈～
