### ISSUE TITLE
Mean AP = 0.6676?

### ISSUE THREAD

**Issue by PumayHui** [YeahHuang/Al_surface_defect_detection#2]
Hello, @YeahHuang 
I train my own dataset with the config file"tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.yaml", and the result of test_net.py is : 

INFO voc_dataset_evaluator.py: 145: Mean AP = 0.6124
INFO voc_dataset_evaluator.py: 146: TP = 6802
INFO voc_dataset_evaluator.py: 147: FP = 3439
INFO voc_dataset_evaluator.py: 148: FN = 1388
INFO voc_dataset_evaluator.py: 149: Mean 1-Precision = 0.3358
INFO voc_dataset_evaluator.py: 150: Mean Recall = 0.8305

**I want to increase the recall as far as possible.**
And my dataset is similar to AI_Surface_defect. The classes is 5 + 1(background).

Could you give me some advices? thanks so much!  
[tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.txt](https://github.com/YeahHuang/Al_surface_defect_detection/files/2739664/tutorial_1gpu_e2e_faster_rcnn_R-50-FPN.txt)

**Comment by YeahHuang** [comment]
Just as I mentioned in README,  1) Larger resize size( e.g. SCALES: (500,) -> SCALES: (600, 800, 1000))  , 2) adding bbox vote might be useful. 

If u want to further increase the recall on your own dataset, I strongly recommend u read the config.py(https://github.com/facebookresearch/Detectron/blob/master/detectron/core/config.py)  thoroughly.   Or the Chinese blog(https://blog.csdn.net/zziahgf/article/details/79652946).

Best Wishes!

**Comment by PumayHui** [comment]
Well, thanks so much!

**Comment by PumayHui** [comment]
@YeahHuang 
你好哇
我在使用test.yaml运行infer_simple.py时，GPU显存一直上升，最后就会out of memory，请问你有遇到这个问题吗？
我测试了一下，发现将TEST.BBOX_AUG设置为False时不会出现这种情况，设置为True时，跑大概四五十幅图就会出现out of memory……
感谢~

**Comment by YeahHuang** [comment]
哈哈 就是显存不够嘛 最好的方法就是换个大显存的GPU～ 
我木有遇到过这个问题， 当时跑这个代码的时候 是在极客云上临时租了大显存的gpu的...
当然如果环境不允许 设置成False是可以的， 只不过少了bbox augmentation 至少在我当时的数据集上 mAP是会有下降的， 自己权衡咯～
祝好 :)

**Comment by PumayHui** [comment]
我的显存是11G的 应该不是这个问题~
然后 我解决了  哈哈
就是因为inference输入的图片大小不一致 导致out of memory了……

**Comment by YeahHuang** [comment]
找到理由啦 棒！

**Comment by PumayHui** [comment]
@YeahHuang 
再请问一下哦~
你用大尺寸的图片训练时，比如2048*3500~
是先裁剪为608x608，再进行训练吗？
感谢~

**Comment by jiec-msft** [comment]
@PumayHui 
你好啊，请问在哪里设置BBOX_AUG 为false呢？
谢谢！！！
> @YeahHuang
> 你好哇
> 我在使用test.yaml运行infer_simple.py时，GPU显存一直上升，最后就会out of memory，请问你有遇到这个问题吗？
> 我测试了一下，发现将TEST.BBOX_AUG设置为False时不会出现这种情况，设置为True时，跑大概四五十幅图就会出现out of memory……
> 感谢~

**Comment by PumayHui** [comment]
@ECNUJason 默认就是false啊

**Comment by jiec-msft** [comment]
我手头只有一个2G显存的GPU，在false的情况下就out of memory了，有没有什么办法可以勉强跑一跑呢？
谢谢！！！
@PumayHui

**Comment by PumayHui** [comment]
@ECNUJason 这个不太清楚哎~

**Comment by YeahHuang** [comment]
@ECNUJason  方法1是把图片尺寸再调小很多 方法2 其实我还挺建议去极客云上租一个跑一下的 5元/h 其实还好

**Comment by jiec-msft** [comment]
@YeahHuang 恩，按照你的建议，我已经把Detectron教程里面的infer_simple等等在极客云上面跑起来了。
由于是个新手，还在摸索。我想了解一下你处理数据、然后如何将代码执行起来，比如python tools/xxxx 如何传入参数等。
谢谢！如果你有之前训练好的模型，能不能发我一份呢，我想用infer_simple.py来跑一跑试试！
我摸索清楚以后，打算写一个新手教程，谢谢你！

**Comment by jiec-msft** [comment]
恩，我看到了，在.sh文件里面有些执行的命令！谢谢！！
